import {Router} from 'express';import {verifyFirebaseToken,requireRole,requirePermission} from '../middleware/auth.js';import * as auth from '../controllers/auth.js';import * as users from '../controllers/users.js';import * as quizzes from '../controllers/quizzes.js';import * as staff from '../controllers/staff.js';import * as participants from '../controllers/participants.js';import * as questions from '../controllers/questions.js';
const r=Router();r.get('/auth/me',verifyFirebaseToken,auth.me);r.post('/auth/logout',verifyFirebaseToken,auth.logout);
r.use('/users',verifyFirebaseToken,requireRole('SUPER_ADMIN'));r.get('/users',users.list);r.get('/users/:id',users.get);r.post('/users',users.create);r.patch('/users/:id',users.update);r.delete('/users/:id',users.remove);r.patch('/users/:id/status',users.status);
r.use('/staff',verifyFirebaseToken,requireRole('SUPER_ADMIN'));r.get('/staff',staff.list);r.post('/staff',staff.create);r.get('/staff/:id',async(req,res)=>res.json({id:req.params.id}));r.patch('/staff/:id',staff.patch);r.delete('/staff/:id',staff.remove);r.get('/staff/:id/permissions',staff.permissions);r.patch('/staff/:id/permissions',staff.setPermissions);
r.get('/quizzes',verifyFirebaseToken,requireRole('SUPER_ADMIN','STAFF','USER'),quizzes.list);r.get('/quizzes/:id',verifyFirebaseToken,requireRole('SUPER_ADMIN','STAFF','USER'),quizzes.get);r.post('/quizzes',verifyFirebaseToken,requirePermission('CREATE_QUIZ'),quizzes.create);r.patch('/quizzes/:id',verifyFirebaseToken,requirePermission('EDIT_QUIZ'),quizzes.update);r.delete('/quizzes/:id',verifyFirebaseToken,requirePermission('DELETE_QUIZ'),quizzes.remove);r.post('/quizzes/:id/publish',verifyFirebaseToken,requirePermission('EDIT_QUIZ'),quizzes.publish);r.post('/quizzes/:id/start',verifyFirebaseToken,requirePermission('START_QUIZ'),quizzes.start);r.post('/quizzes/:id/end',verifyFirebaseToken,requirePermission('END_QUIZ'),quizzes.end);r.post('/quizzes/:id/archive',verifyFirebaseToken,requirePermission('DELETE_QUIZ'),quizzes.archive);
r.get('/questions/:quizId',verifyFirebaseToken,requireRole('SUPER_ADMIN','STAFF','USER'),questions.list);r.post('/questions/:quizId',verifyFirebaseToken,requirePermission('EDIT_QUIZ'),questions.create);r.patch('/questions/:quizId/:questionId',verifyFirebaseToken,requirePermission('EDIT_QUIZ'),questions.update);r.delete('/questions/:quizId/:questionId',verifyFirebaseToken,requirePermission('DELETE_QUIZ'),questions.remove);
r.post('/join/:joinCode',participants.join);r.get('/participant/session/:sessionId',participants.session);r.post('/participant/session/:sessionId/answer',participants.answer);r.post('/participant/session/:sessionId/complete',participants.complete);r.get('/participant/session/:sessionId/result',participants.result);
r.get('/analytics',verifyFirebaseToken,requirePermission('VIEW_ANALYTICS'),async(_req,res)=>res.json({completedSessions:0,participants:0}));r.get('/activity',verifyFirebaseToken,requireRole('SUPER_ADMIN'),async(_req,res)=>{const {db}=await import('../config/firebase.js');const s=await db.collection('activityLogs').orderBy('createdAt','desc').limit(200).get();res.json({items:s.docs.map(d=>({id:d.id,...d.data()}))})});r.get('/settings',verifyFirebaseToken,requireRole('SUPER_ADMIN'),async(_req,res)=>res.json({ok:true}));
export default r;
